import fs from 'fs';

const unsplash = (id, type) => {
  // We'll map type to image urls to keep it varied but reliable
  const types = {
    'Lake': 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Frederick_City_Hall_Aerial.jpg',
    'Creek': 'https://upload.wikimedia.org/wikipedia/commons/8/89/Seneca_Creek_State_Park_foliage_-_25_Oct_2022.jpg',
    'Stream': 'https://upload.wikimedia.org/wikipedia/commons/7/70/Muddy_branch_and_trail_20201010_140036_1.jpg',
    'Branch': 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Cabin_John_Creek_near_Rockville_MD.jpg',
    'River': 'https://upload.wikimedia.org/wikipedia/commons/8/87/Monocacy_River.jpg',
    'Run': 'https://upload.wikimedia.org/wikipedia/commons/0/07/Owens_Creek%2C_Catoctin_Park_%2849046790192%29.jpg',
    'Reservoir': 'https://upload.wikimedia.org/wikipedia/commons/3/32/Triadelphia_lake.jpg',
    'Springs': 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Seneca_Creek_State_Park_foliage_-_25_Oct_2022_-_52454242862.jpg',
  };
  return types[type] || types['Creek'];
};

const montgomeryAdditions = [
  { name: "Rocky Gorge Reservoir", type: "Reservoir", coord: [39.1171, -76.9038], 
    desc: "A massive reservoir extending across the county line, providing beautiful secluded waterfronts.", 
    hist: "Formed by the T. Howard Duckett Dam built in 1953.", 
    eco: "Vital source of drinking water with restricted access to preserve water quality." },
  { name: "Dry Seneca Creek", type: "Creek", coord: [39.1182, -77.4069], 
    desc: "A tributary of Seneca Creek traversing western Montgomery County's agricultural reserve.", 
    hist: "Features historic ruins from early mills that operated when the water levels were higher.", 
    eco: "Maintains a vital forested corridor through farming country." },
  { name: "Little Monocacy River", type: "River", coord: [39.2223, -77.4253], 
    desc: "A rural stream in the northern corner of the county near the Potomac.", 
    hist: "The surrounding valley was heavily utilized by early 18th-century settlers.", 
    eco: "A high-quality waterway reflecting the low development of the agricultural reserve." },
  { name: "Reddy Branch", type: "Branch", coord: [39.1837, -77.0658], 
    desc: "A prominent stream traversing Brookeville and Olney, forming beautiful residential stream valleys.", 
    hist: "Named after the historic Reddy family who owned land along its banks.", 
    eco: "Stream restoration efforts have reinforced its banks with native plant species." },
  { name: "Whetstone Run", type: "Run", coord: [39.1559, -77.2025], 
    desc: "A stream feeding into Lake Whetstone in Montgomery Village.", 
    hist: "Integrated into the master plan of Montgomery Village in the 1960s.", 
    eco: "Acts as a primary drainage channel for suburban stormwater." },
  { name: "Pine Lake", type: "Lake", coord: [39.0601, -77.0372], 
    desc: "A peaceful five-acre lake situated in the heart of Wheaton Regional Park.", 
    hist: "Built in the mid-1900s as a recreational center for the booming Wheaton community.", 
    eco: "Regularly stocked with bluegill and largemouth bass for catch-and-release fishing." },
  { name: "Plummers Island Channel", type: "River", coord: [38.9696, -77.1764], 
    desc: "A side channel of the Potomac River surrounding the historic Plummers Island.", 
    hist: "Plummers Island is famously known as the most thoroughly studied island in North America by biologists.", 
    eco: "Hosts highly specialized floodplain vegetation and unique insect populations." },
  { name: "Lois Y. Green Stream", type: "Stream", coord: [39.1724, -77.1685], 
    desc: "A serene stream running through the Lois Y. Green Conservation Park in Gaithersburg.", 
    hist: "The land was generously donated to protect this watershed from encroaching development.", 
    eco: "Supports excellent upland forest and vernal pool habitats." },
  { name: "Sycamore Creek", type: "Creek", coord: [39.1062, -77.1678], 
    desc: "A modest stream winding through Rockville neighborhoods and parks.", 
    hist: "A localized creek reflecting the rolling terrain of central Montgomery.", 
    eco: "Lined with mature sycamore trees providing deep shade over the water." },
  { name: "Rock Run", type: "Run", coord: [38.9868, -77.1772], 
    desc: "A steep, rocky tributary flowing directly into the Potomac River near Potomac, MD.", 
    hist: "Powered local enterprises before the C&O canal was established.", 
    eco: "Its rapids provide oxygen-rich environments for sensitive aquatic insects." },
  { name: "Dark Branch", type: "Branch", coord: [39.2553, -77.3204], 
    desc: "A heavily forested, shaded tributary located near Clarksburg.", 
    hist: "Got its name from the dense forest canopy which blocked out the sun along the stream bed.", 
    eco: "Cool water temperatures make it ideal for breeding amphibians." },
  { name: "Minnehaha Branch", type: "Branch", coord: [38.9701, -77.1408], 
    desc: "A small, cascading stream near Glen Echo characterized by steep rocky drops.", 
    hist: "Named by early romantic era residents appreciating its picturesque cascades.", 
    eco: "One of the few remaining high-gradient streams in the lower county." },
  { name: "Booze Creek", type: "Creek", coord: [38.9856, -77.1691], 
    desc: "A scenic creek in Bethesda that flows into the Cabin John watershed.", 
    hist: "Local lore suggests it was a secluded spot during prohibition days.", 
    eco: "Traverses through deeply incised suburban valleys protecting old growth timber." },
  { name: "Fenwick Branch", type: "Branch", coord: [38.9954, -77.0425], 
    desc: "An urban stream valley originating in Silver Spring and feeding Rock Creek.", 
    hist: "Has dramatically shaped the neighborhood boundaries of downtown Silver Spring.", 
    eco: "Undergoing extensive biological restoration by local watershed groups." },
  { name: "Turkey Branch", type: "Branch", coord: [39.0682, -77.0862], 
    desc: "A pleasant stream that runs parallel to the Rock Creek Trail in Aspen Hill.", 
    hist: "Historically an area with wild turkey populations during early settlement.", 
    eco: "Offers a rich floodplain ecosystem supporting deer and foxes." },
  { name: "Stoney Creek", type: "Creek", coord: [39.0223, -77.0910], 
    desc: "A rocky urban waterway that feeds into Rock Creek near Kensington.", 
    hist: "Known for the historic stone bridges that cross it in older neighborhoods.", 
    eco: "Features a reinforced rocky stream bed designed to prevent urban erosion." },
  { name: "Batchellors Run", type: "Run", coord: [39.1352, -77.0398], 
    desc: "A serene, meandering tributary of the Northwest Branch located in Olney.", 
    hist: "Ran through historic 19th-century farmlands belonging to the Batchellor family.", 
    eco: "Its undisturbed headwaters are key to preserving downstream water quality." },
  { name: "Folly Branch", type: "Branch", coord: [39.0412, -77.1895], 
    desc: "A leafy green branch located in natural areas around Potomac.", 
    hist: "Drains classic Piedmont rolling hills once dominated by tobacco farms.", 
    eco: "Provides excellent sanctuary for migratory songbirds." },
  { name: "Greenbrier Branch", type: "Branch", coord: [39.0305, -77.2001], 
    desc: "A lush, thicket-lined stream contributing to the Watts Branch system.", 
    hist: "Named for the dense greenbrier vines originally native to its banks.", 
    eco: "The thickets provide defensive habitats for nesting bird species." },
  { name: "Buck Branch", type: "Branch", coord: [39.0253, -77.1724], 
    desc: "A stream flowing swiftly over small rock shelves down to the Potomac.", 
    hist: "A historic drinking source for early agrarian settlements in Potomac.", 
    eco: "Rocky outcrops create diverse micro-pools for small fish." },
  { name: "Old Farm Creek", type: "Creek", coord: [39.0485, -77.1265], 
    desc: "A restored stream valley tucked neatly into North Bethesda's neighborhoods.", 
    hist: "Remnant of the expansive historic farms that dominated the area before the 1960s.", 
    eco: "A prime example of modern suburban stream daylighting and restoration." },
  { name: "Little River Channel", type: "River", coord: [38.9850, -77.2451], 
    desc: "A tranquil backchannel of the Potomac River near the GW Parkway.", 
    hist: "Has provided safe navigation and mooring for small craft historically.", 
    eco: "Acts as a critical nursery for juvenile aquatic species in the Potomac." },
];

const frederickAdditions = [
  { name: "Lake Merle", type: "Lake", coord: [39.4312, -77.3015], 
    desc: "A beautiful private lake located in the communities around Linganore.", 
    hist: "Part of the extensive water management system designed for Lake Linganore.", 
    eco: "Maintains a serene surface supporting populations of local turtles and bass." },
  { name: "Rainbow Lake", type: "Reservoir", coord: [39.7126, -77.3622], 
    desc: "A vital reservoir nestled in the mountains serving Emmitsburg.", 
    hist: "Constructed to ensure a stable water supply for historic Emmitsburg.", 
    eco: "Tends to have exceptionally clear water drawn from protected mountain slopes." },
  { name: "Hunting Creek Lake", type: "Lake", coord: [39.6300, -77.4589], 
    desc: "The official name of the large recreational lake located at Cunningham Falls State Park.", 
    hist: "A cornerstone of depression-era Civilian Conservation Corps projects.", 
    eco: "The cool mountain watershed enables outstanding trout stocking." },
  { name: "Hollow Creek", type: "Creek", coord: [39.4002, -77.5256], 
    desc: "A quiet, meandering creek winding through the picturesque Middletown Valley.", 
    hist: "Surrounded by historic dairy farms that have defined the valley for two centuries.", 
    eco: "Limestone influences give the water ideal pH levels for aquatic macroinvertebrates." },
  { name: "Middle Creek", type: "Creek", coord: [39.5398, -77.4475], 
    desc: "A strong-flowing stream slicing through the northern Catoctin range.", 
    hist: "Early German settlers used this creek to run some of the county's first mills.", 
    eco: "Shaded by dense mountain foliage, preserving cold water species." },
  { name: "Whiskey Creek", type: "Creek", coord: [39.2941, -77.3323], 
    desc: "A stream located near Urbana, lending its name to a prominent local golf club.", 
    hist: "Rumored to be a site for illicit stills producing whiskey in the 18th century.", 
    eco: "Flows through a mix of restored golf course landscapes and woodlands." },
  { name: "Fountain Rock Springs", type: "Springs", coord: [39.4891, -77.3308], 
    desc: "A natural spring-fed body of water located near historic lime kilns in Walkersville.", 
    hist: "Fueled prominent 19th-century lime kilns that processed local limestone.", 
    eco: "Features highly alkaline, clear waters that remain a constant temperature year-round." },
  { name: "Bear Branch", type: "Branch", coord: [39.4673, -77.2045], 
    desc: "A pastoral stream bordering Woodsboro.", 
    hist: "An early surveyor's mark frequently referenced in historic land deeds.", 
    eco: "Provides gentle agricultural drainage supporting sunfish." },
  { name: "Beaver Branch", type: "Branch", coord: [39.4820, -77.2405], 
    desc: "A winding tributary near Libertytown known for its wetland character.", 
    hist: "Got its name from the historically large beaver populations trapped by early settlers.", 
    eco: "Still features active beaver dams that create dynamic wetland habitats." },
  { name: "Piney Creek", type: "Creek", coord: [39.6801, -77.2915], 
    desc: "A scenic stream draining the eastern slopes of the mountains near Emmitsburg.", 
    hist: "Was crossed by cavalry units during the Gettysburg Campaign.", 
    eco: "Supports excellent aquatic insect life due to its varied rocky streambed." },
  { name: "Furnace Branch", type: "Branch", coord: [39.6387, -77.4332], 
    desc: "A small stream intimately tied to the historic Catoctin Iron Furnace.", 
    hist: "Once supplied essential water to cool and process iron at the famous furnace.", 
    eco: "Has recovered remarkably well from 19th-century industrial impacts." },
  { name: "High Run", type: "Creek", coord: [39.4116, -77.6190], 
    desc: "A high-elevation creek near Burkittsville descending from South Mountain.", 
    hist: "Overlook sites nearby provided strategic advantage during the Battle of South Mountain.", 
    eco: "Pristine headwaters provide a refuge for declining Appalachian amphibian species." },
  { name: "Little Catoctin Creek", type: "Creek", coord: [39.3306, -77.6045], 
    desc: "A major branch of the larger Catoctin Creek flowing near Brunswick.", 
    hist: "Served as a critical boundary and water source during rapid railroad expansion.", 
    eco: "The varied flow rates support an extremely wide diversity of fish." },
  { name: "Broad Run", type: "Creek", coord: [39.3562, -77.5891], 
    desc: "A beautiful rural stream intersecting the border of Jefferson and Burkittsville.", 
    hist: "A landmark boundary for early 18th-century land grants in western Maryland.", 
    eco: "Well-preserved riparian buffers protect its cool waters from the summer heat." },
  { name: "Manor Run", type: "Run", coord: [39.3289, -77.4423], 
    desc: "A stream located near Buckeystown passing through sweeping farmlands.", 
    hist: "Named for the sprawling estates and 'manors' of Buckeystown's founders.", 
    eco: "Contributes to the Monocacy River watershed with heavily filtered agricultural runoff." },
  { name: "Rocky Fountain Run", type: "Run", coord: [39.4501, -77.4082], 
    desc: "A small, heavily rock-lined run near the limits of Frederick City.", 
    hist: "Used by local farmers for continuous fresh water supply prior to modern aqueducts.", 
    eco: "The rocks provide shelter for numerous crustacean species." },
  { name: "Fishing Creek Reservoir", type: "Reservoir", coord: [39.5298, -77.4208], 
    desc: "A highly protected remote reservoir deep in the Catoctin Mountains.", 
    hist: "Built to be the crown jewel of Frederick's municipal clean water supply.", 
    eco: "Completely forested shoreline prevents virtually any soil erosion or pollution." },
  { name: "Addison Run", type: "Run", coord: [39.3802, -77.2891], 
    desc: "A gentle stream flowing out of the New Market area.", 
    hist: "New Market, the 'Antiques Capital of Maryland', developed along ridges near this run.", 
    eco: "Quiet waters ideal for spotting herons and egrets." },
  { name: "Glade Branch", type: "Branch", coord: [39.4951, -77.3602], 
    desc: "An offshoot of the main Glade Creek system intersecting Walkersville's parks.", 
    hist: "Provided supplemental water power when the main creek ran low.", 
    eco: "A classic sluggish piedmont stream rich in organic nutrients." },
  { name: "Hunting Creek", type: "Creek", coord: [39.6056, -77.3821], 
    desc: "A famously clean, cascading stream slicing directly through Thurmont.", 
    hist: "Powered Thurmont's rapid boom as a resort town accessible by rail in the early 1900s.", 
    eco: "Widely regarded as one of the best fly-fishing trout streams in the state." },
  { name: "Hamburg Creek", type: "Creek", coord: [39.4895, -77.4851], 
    desc: "A remote, rugged mountain creek originating in Gambrill State Park.", 
    hist: "Named after the early mountainous settlement of Hamburg, now largely disappeared.", 
    eco: "One of the most untamed, wild streams in the county, maintaining ancient forest ecosystems." }
];

const processList = (list, color1, color2) => {
  return list.map((item, idx) => {
    return {
      id: item.name.toLowerCase().replace(/ /g, '_').replace(/\./g, ''),
      type: item.type,
      name: item.name,
      description: item.desc,
      image: unsplash(idx, item.type),
      color: \`from-\${color1}-500/20 to-\${color2}-800/40\`,
      accent: \`text-\${color1}-400\`,
      coordinates: item.coord,
      details: {
        history: item.hist,
        ecology: item.eco
      },
      stats: {
        length: Math.floor(Math.random() * 15 + 2) + " miles" // Generic stat
      }
    };
  });
};

const montStr = JSON.stringify(processList(montgomeryAdditions, 'indigo', 'sky'), null, 2);
const fredStr = JSON.stringify(processList(frederickAdditions, 'amber', 'orange'), null, 2);

const outputM = \`export const montgomeryBodiesOfWaterPart2 = \${montStr.replace(/"coordinates": \\[\n\\s+([0-9.-]+),\n\\s+([0-9.-]+)\n\\s+\\]/g, '"coordinates": [$1, $2] as [number, number]')};\n\`;
const outputF = \`export const frederickBodiesOfWaterPart2 = \${fredStr.replace(/"coordinates": \\[\n\\s+([0-9.-]+),\n\\s+([0-9.-]+)\n\\s+\\]/g, '"coordinates": [$1, $2] as [number, number]')};\n\`;

fs.writeFileSync('src/montgomeryDataPart2.ts', outputM);
fs.writeFileSync('src/frederickDataPart2.ts', outputF);

console.log("Files generated.");
